blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import login_view, logout_view, register_view
from .views import post_redirect_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls')),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('posts/', include('posts.urls')),
    path('', post_redirect_view),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path

from .views import post_list, post_create, post_detail, post_update, post_delete

app_name = 'posts'

urlpatterns = [
	path('', post_list, name='list'),
    path('create', post_create, name='create'),
    path('<slug:slug>', post_detail, name='detail'),
    path('<slug:slug>/edit', post_update, name='update'),
    path('<slug:slug>/delete', post_delete, name='delete'),
]

posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown

from comments.models import Comment
from .utils import get_read_time
# Create your models here.


class PostManager(models.Manager):

	def active(self,*args,**kwargs):
		return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
	title 			= models.CharField(max_length = 256)
	image 			= models.ImageField(null=True, blank=True, width_field='width_field', height_field='height_field')
	slug 			= models.SlugField(unique=True)
	height_field 	= models.IntegerField(default=0)
	width_field 	= models.IntegerField(default=0)
	content 		= models.TextField()
	draft 			= models.BooleanField(default=False)
	publish 		= models.DateField(auto_now=False, auto_now_add=False)
	read_time		= models.IntegerField(null=True, blank=True)
	created_on 		= models.DateTimeField(auto_now_add = True)
	updated_on 		= models.DateTimeField(auto_now = True)

	objects = PostManager()

	class Meta:
		ordering = ['-created_on', '-updated_on']
		
	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:detail', kwargs={'slug':self.slug})

	def get_delete_url(self):
		return reverse('posts:delete', kwargs={'slug':self.slug})

	def get_edit_url(self):
		return reverse('posts:update', kwargs={'slug':self.slug})

	def get_markdown(self):
		return mark_safe(markdown(self.content))

	@property	
	def comments(self):
		return Comment.objects.filter_by_instance(self)

	@property
	def get_content_type(self):
		return ContentType.objects.get_for_model(self.__class__)


def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug

	qs = Post.objects.filter(slug=slug).order_by('-id')

	if qs.exists():
		new_slug = "%s-%s" %(slug,qs.first().id)
		return create_slug(instance, new_slug)
	return slug



def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug or Post.objects.filter(slug=instance.slug).exists():
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time = get_read_time(html_string)
		instance.read_time = read_time


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from .models import Post
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):

	publish = forms.DateField(widget=forms.SelectDateWidget)
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	class Meta:
		model = Post
		fields = [
		'title',
		'content',
		'image',
		'draft',
		'publish',
		]

posts/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.exceptions import PermissionDenied

from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404

from comments.models import Comment
from comments.forms import CommentForm
from .models import Post
from .forms import PostForm
from .utils import get_read_time

import urllib
# Create your views here.

def post_list(request):
	if not request.user.is_staff or not request.user.is_superuser:
		queryset_list = Post.objects.active()
	else:
		queryset_list = Post.objects.all()

	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query)|
				Q(user__last_name__icontains=query)
			).distinct()

	paginator = Paginator(queryset_list, 6)
	page = request.GET.get('page')
	try:
		queryset = paginator.get_page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)

	context = {
		'objects': queryset,
		'title': 'List'
	}
	return render(request, 'post_list.html', context)


def post_detail(request,slug=None):
	instance = get_object_or_404(Post,slug=slug)
	if instance.draft or instance.publish > timezone.now().date():
		print(instance.draft)
		print(timezone.now().date())
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404

	initial_data = {
		'content_type': instance.get_content_type,
		'object_id': instance.id
	}

	comments = instance.comments
	comment_form = CommentForm(request.POST or None, initial=initial_data)

	if request.POST:
		if not request.user.is_authenticated:
			return redirect('/login/?next={slug}'.format(slug=slug))
		if comment_form.is_valid():
			c_type = comment_form.cleaned_data.get("content_type")
			content_type = ContentType.objects.get(model=c_type)
			object_id = comment_form.cleaned_data.get("object_id")
			content = comment_form.cleaned_data.get("content")
			parent_obj = None

			try:
				parent_id = int(request.POST.get('parent_id'))
			except:
				parent_id = None

			if parent_id:
				parent_qs = Comment.objects.filter(id=parent_id)
				if parent_qs.exists():
					parent_obj = parent_qs.first()


			new_comment, created = Comment.objects.get_or_create(
								user=request.user,
								content_type=content_type,
								object_id=object_id,
								content=content,
								parent=parent_obj,
							)
			return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	context = {
		'title': instance.title,
		'instance': instance,
		'comments': comments,
		'comment_form': comment_form, 
	}
	return render(request, 'post_detail.html', context)


def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise PermissionDenied
	form = PostForm(request.POST or None, request.FILES or None)
	if request.POST:
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			messages.success(request, 'Successfully Created.')
			return HttpResponseRedirect(instance.get_absolute_url())
		else:
			messages.error(request, 'Not Successfully Created.')
	context = {
		'title': 'New Post',
		'form': form,

	}
	return render(request, 'post_form.html', context)


def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise PermissionDenied
	instance = get_object_or_404(Post,slug=slug)
	if request.user != instance.user:
		raise PermissionDenied
	form = PostForm(request.POST or None, request.FILES or None, instance = instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, 'Saved.')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		'title': 'New Post',
		'form': form,

	}
	context = {
		'title': instance.title,
		'instance': instance,
		'form': form
	}
	return render(request, 'post_form.html', context)


def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise PermissionDenied
	instance = get_object_or_404(Post, slug=slug)
	if request.user != instance.user:
		raise PermissionDenied

	if request.method == 'POST':
		instance.delete()
		messages.success(request,'Post Deleted.')
		return HttpResponseRedirect('/posts/')

	context = {
		'obj': instance
	}
	return render(request, 'post_delete.html', context)

templates/505.html
{% extends 'base.html' %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">
		<p class="lead">
			505 Error! Internal Server Error. Please try again later.
		</p>
	</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
	<title>{% block head_title %}Blog{% endblock %}</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

	{% block head_extra %}{% endblock %}
</head>
<body>

	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.0';
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	{% include 'message_display.html' %}
	
	<div class="col-sm-8 col-sm-offset-2">
		<ol class="breadcrumb">
			<li><a href="{% url 'posts:list' %}">Home</a></li>
			{% block post_detail_link %}
			{% endblock %}
			{% if not request.user.is_authenticated %}
				<li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
				<li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
			{% else %}
				<li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
			{% endif %}
		</ol>
	</div>

	{% block content %}
		
	{% endblock %}
	
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js">
	</script>

	<script type="text/javascript" src="{% static "js/base.js" %}"></script>

</body>
</html>

templates/comment_delete.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
	{{ block.super }} | Comments
{% endblock %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Confirm Delete</h1>

			<form method="POST" action="">
				{% csrf_token %}
				<blockquote>
						<p>{{ comment.content }}</p>
						<footer><strong>{{ comment.user.get_full_name }} </strong>| {{ comment.created_on|timesince }} ago |{% if comment.children.count > 0 %} {{ comment.children.count }} Repl{% endif %}{% if comment.children.count > 1 %}ies | {% elif comment.children.count > 0 %}y | {% endif %}<a href="#" class="comment-reply-btn"> Reply</a> | <a href="{{ comment.get_absolute_url }}"> Thread</a></footer>
				</blockquote>
				<p>Are you sure you want to delete this comment? This will also delete all its replies.</p>
				<input type="submit" class="btn btn-danger" value="Delete">
				<a href="{{ comment.get_absolute_url }}" class="btn btn-default">Cancel</a>
			</form>
		</div>

	</div>
{% endblock %}

templates/comment_thread.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
	{{ block.super }} | Comments
{% endblock %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">
		
		<p>{{ comment.content }}</p>
		<footer><strong>{{ comment.user.get_full_name }} </strong>| {{ comment.created_on|timesince }} ago {% if comment.children.count > 0 %}| {{ comment.children.count }} Repl{% endif %}{% if comment.children.count > 1 %}ies{% elif comment.children.count > 0 %}y{% endif %} {% if request.user == comment.user or request.user.is_staff %}<a href="{{ comment.get_delete_url }}">Delete </a>{% endif %}</footer>

		<hr />
		
		<div>
			{% for child_comment in comment.children %}
				<blockquote>
					<p>{{ child_comment.content }}</p>
					<footer><strong>{{ child_comment.user.get_full_name }} </strong>| {{ child_comment.created_on|timesince }} ago {% if request.user == child_comment.user or request.user.is_staff %}<a href="{{ child_comment.get_delete_url }}">Delete </a>{% endif %}
					</footer>
				</blockquote>
			{% endfor %}


			<form method="POST" action="">
				{% csrf_token %}
				{{ form|crispy }}
				<input type="hidden" name="parent_id" value="{{ comment.id }}">
				<input type="submit" class="btn btn-default" value="Reply">
			</form>				
		
		</div>
	</div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
	{{ block.super }} | {{ title }}
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				<h1>{{ title }}</h1>
				<hr />
				{% if form %}
					{% if next %}
					<form method="POST" enctype="multipart/form-data" action="/{{ title|lower }}/?next={{ next }}">
					{% else %}
					<form method="POST" enctype="multipart/form-data" action=".">
					{% endif %}
						{% csrf_token%}
						{{ form|crispy }}
						<div class="col-sm-4 col-sm-offset-4"> 
							<input class="form-control btn btn-primary" type="submit" name="submit" value="{{ title }}">
						</div>
					</form>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/message_display.html
{% if messages %}
	<div class="messages">
		<ul class="messages">
		    {% for message in messages %}
			    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
	</div>
{% endif %}

templates/post_delete.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
	{{ block.super }} | Comments
{% endblock %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Confirm Delete</h1>

			<form method="POST" action="">
				{% csrf_token %}
				<div class="thumbnail">
					{% if obj.image %}
						<img src="{{ obj.image.url }}" class="img-responsive">
					{% endif %}
					<div class="caption post-detail-item">
						<h3>
							<a href="{{ obj.get_absolute_url }}">
								{{ obj.title }}
							</a>
							<small>
								{% if obj.draft %}
								<span style="color:red">
									Draft
								</span>
								{% endif %}
								{{ obj.publish }}
							</small>
						</h3>
						{% if obj.user.get_full_name %}
							<p>Author: {{ obj.user.get_full_name }}</p>
						{% endif %}			
						{{ obj.get_markdown|truncatechars:80 }}
						<p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
					</div>					
				</div>

				<p>Are you sure you want to delete this post? This will also delete all its comments.</p>
				<input type="submit" class="btn btn-danger" value="Delete">
				<a href="{{ obj.get_absolute_url }}" class="btn btn-default">Cancel</a>
			</form>
			<br/>
		</div>

	</div>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
	{{ block.super }} | {{ instance.title }}
{% endblock %}

{% block post_detail_link %}
	<li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
	{% if instance %}
		<div class="col-sm-6 col-sm-offset-3">
			{% if instance.image %}
				<img src="{{ instance.image.url }}" class="img-responsive">
			{% endif %}
			<h1>{{ instance.title }} 
				<small>
					{% if instance.draft %}
					<span style="color:red">
						Draft
					</span>
					{% endif %}
					{{ instance.publish }}
				</small>
			</h1><br />
			<p>
				{% if instance.user.get_full_name %}
					<span>Author: {{ instance.user.get_full_name }}</span>
				{% endif %}

				<span class="read-time">Read time: {% if instance.read_time <= 1 %}< 1 minute {% else %}{{ instance.read_time }} minutes{% endif %}</span>
			</p>			

			<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>

			<hr />

			<div class="row">
				<div class="col-sm-12 post-detail-item">
					{{ instance.get_markdown }}<br />
				</div>
			</div>

			{% if request.user == instance.user %}
				<div class="row">
					<span class="detail-post-delete-btn">
						<a href="{{ instance.get_delete_url }}" class="btn btn-danger">Delete</a>
					</span>
					<span class="detail-post-edit-btn">
						<a href="{{ instance.get_edit_url }}" class="btn btn-primary">Edit</a>
					</span>
					
				</div>
			{% endif %}

			<hr />
			<br />

			<div>
				<p class="lead">Comments</p>
				<hr />
				<div style="padding-bottom: 15px">
					<form method="POST" action="">
						{% csrf_token %}
						{{ comment_form|crispy }}
						<input type="submit" class="btn btn-default" value="Post Comment">
					</form>
				</div>
				{% for comment in comments %}
					<blockquote>
						<p>{{ comment.content }}</p>
						<footer><strong>{{ comment.user.get_full_name }} </strong>| {{ comment.created_on|timesince }} ago |{% if comment.children.count > 0 %} {{ comment.children.count }} Repl{% endif %}{% if comment.children.count > 1 %}ies | {% elif comment.children.count > 0 %}y | {% endif %}<a href="#" class="comment-reply-btn"> Reply</a> | <a href="{{ comment.get_absolute_url }}"> Thread</a>{% if request.user == comment.user or request.user.is_staff %}<a href="{{ comment.get_delete_url }}"> | Delete </a>{% endif %}</footer>

						<div class="comment-reply">
							{% for child_comment in comment.children %}
								<blockquote>
									<p>{{ child_comment.content }}</p>
									<footer><strong>{{ child_comment.user.get_full_name }} </strong>| {{ child_comment.created_on|timesince }} ago{% if request.user == child_comment.user or request.user.is_staff %}<a href="{{ child_comment.get_delete_url }}"> Delete </a>{% endif %}</footer>
								</blockquote>
							{% endfor %}

							<form method="POST" action="">
								{% csrf_token %}
								{{ comment_form|crispy }}
								<input type="hidden" name="parent_id" value="{{ comment.id }}">
								<input type="submit" class="btn btn-default" value="Reply">
							</form>

						</div>

					</blockquote>	
				{% endfor %}
				<hr />
			</div>

		</div>
	{% endif %}
{% endblock %}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
	{{ block.super }} | New Post 
{% endblock %}

{% block head_extra %}
	{{ form.media }}
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h1>Form</h1>
				<hr />
				{% if form %}
					<form method="POST" enctype="multipart/form-data" action="">
						{% csrf_token%}
						{{ form|crispy }}
						<div class="col-sm-4 col-sm-offset-3"> 
							<input class="form-control btn btn-primary" type="submit" name="submit" value="Post">
						</div>
					</form>
				{% endif %}
			</div>

			<div class="col-sm-6">
				<h1> Preview </h1>
				<hr />
				<div class="content-preview">
					<h3 id="preview-title"></h3>
					<p id="preview-content"></p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}

{% block head_title %}
	{{ block.super }} | Posts 
{% endblock %}

{% block content %}

	<div class="col-sm-6 col-sm-offset-3">
		<h1>{{ title }}</h1>

		<form method="GET" action="" class="row">
			<div class="col-sm-6">
				<div class="input-group" style="padding-bottom: 20px">
					<input type="text" name="q" class="form-control" placeholder="Search for..." value="{{ request.GET.q }}">
					<span class="input-group-btn">
						<button class="btn btn-default" type="submit">Search</i></button>
					</span>
				</div>
			</div>
		</form>
	
		{% for obj in objects %}
			<div class="row">
				<div class="col-sm-12">
					<div class="thumbnail">
						{% if obj.image %}
							<img src="{{ obj.image.url }}" class="img-responsive">
						{% endif %}
						<div class="caption post-detail-item">
							<h3>
								<a href="{{ obj.get_absolute_url }}">
									{{ obj.title }}
								</a>
								<small>
									{% if obj.draft %}
									<span style="color:red">
										Draft
									</span>
									{% endif %}
									{{ obj.publish }}
								</small>
							</h3>
							{% if obj.user.get_full_name %}
								<p>Author: {{ obj.user.get_full_name }}</p>
							{% endif %}			
							{{ obj.get_markdown|truncatechars:80 }}
							<p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
						</div>					
					</div>
				</div>
			</div>
		{% endfor %}

		{% if objects.has_other_pages %}
			<div class="col-sm-offset-2">
			<ul class="pagination">
				{% if objects.has_previous %}
					<li class="page-item"><a class="page-link" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ objects.previous_page_number }}">&laquo;</a></li>
				{% else %}
					<li class="page-item disabled"><span>&laquo;</span></li>
				{% endif %}
				{% for i in objects.paginator.page_range %}
					{% if objects.number == i %}
						<li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
					{% else %}
						<li class="page-item"><a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ i }}">{{ i }}</a></li>
					{% endif %}
				{% endfor %}
				{% if objects.has_next %}
					<li class="page-item"><a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ objects.next_page_number }}">&raquo;</a></li>
				{% else %}
					<li class="page-item disabled"><span>&raquo;</span></li>
				{% endif %}
			</ul>
		</div>
		{% endif %}

	</div>
{% endblock %}